### ISSUE TITLE
[UI] Implement Cart UI

### ISSUE THREAD

**Issue by doannimble** [nimblehq/showcase_flutter_build_ios_android#4]
## Why

At the staff screen, we need to display the cart so that the staff can add/remove or update the quantity of the items.

![Untitled](https://github.com/nimblehq/showcase_flutter_build_ios_android/assets/88996251/7c092086-f250-4854-a6f9-eda26fa386a4)

## Who Benefits?

Staff

**Comment by Shayokh144** [comment]
@doannimble web-desktop project already have [this](https://github.com/nimblehq/showcase-flutter-build-web-desktop/pull/15) , can we reuse them rather than creating new as we forked the repo from that?

**Comment by doannimble** [comment]
@Shayokh144 We can reuse this, but please make it supports for displaying with phone/tablet too 🙏

**Comment by Shayokh144** [comment]
@doannimble the width of mobile screen is too small to show both product and cart in same screen, for tablet it's ok, should we change UI for mobile screen?

**Comment by doannimble** [comment]
correct @Shayokh144 , we should change UI for the mobile screen. But please do it is a low priority, please focus on the other areas first
cc @thiennguyen0196
