### ISSUE TITLE
Integrate Cart at the Staff screen

### ISSUE THREAD

**Issue by doannimble** [nimblehq/showcase_flutter_build_ios_android#5]
## Why

At the staff screen, the use should be able to add/remove/modify the item in the cart. These actions should be sent to Customer display

## Who Benefits?

Staff user

**Comment by thiennguyen0196** [comment]
This has been resolved in #7

**Comment by thiennguyen0196** [comment]
This issue will be re-assigned to you @doannimble 🤝

**Comment by doannimble** [comment]
Tested and confirmed, resolved.
